### ISSUE TITLE
Map UI

### ISSUE THREAD

**Issue by urgent** [urgent/thisbounty.com#21]
Try react-canvas please, previous react-storm.

If that doesn't work, fallback to fabric.js

**Comment by urgent** [comment]
![Screenshot_2019-06-01 thisbounty com - No Catch, No Pay](https://user-images.githubusercontent.com/1377758/58747852-cdf90a80-843e-11e9-9bd2-4a5f0075b5e4.png)

**Comment by urgent** [comment]
@adammankowski1 May you please work on a presentation component?

I want to send a <Map /> react component with properties like:

const Wardleys = [ <Wardley valueChain="2" maturity="9" label="Bulma" icon=<Icon src="../img/bulma.svg"> ]

<Map items=<Wardleys /> />

**Comment by urgent** [comment]
I'm thinking we have three components:

Wardley: Shows an individual icon
Wardleys: Manages the connectors and positions
Map: Handles the user controls, panning and zooming

That code needs some work, just thinking on paper. Like Wardley is an array, and the Map is expecting a React component.

Do you think you will need one task for this or two? Current rate for tasks is $25 each.

Let me know please, and I will either work more here to get it down into one, or readjust my budget.

Thank you again Adam!

**Comment by adammankowski1** [comment]
Hi, let it be one task. I've done research. Have you considered using d3?
https://bl.ocks.org/cjrd/6863459
as well https://github.com/drffej/VCMapEditor

I've done something this below in VCMapEditor. It should be possible to change circles with icons.

![Przechwytywanie](https://user-images.githubusercontent.com/4780115/58751450-d3863d00-849e-11e9-90a1-460e2c20085b.PNG)

I know the numerator in valueChain is Y axis, and maturity should be X axis, but what means numerator and denumerator values there?

I'm thinking how to create such map. My first thought was table, but it would limit us with controls, so finally I think we would end up with map as just div with another div as components with some translating options (values and maturity to width/height pixels).

**Comment by urgent** [comment]
Yes that's perfect.

**Comment by urgent** [comment]
https://gridbyexample.com/examples/

Like this is built into every browser now, and is super easier than flexbox.

**Comment by urgent** [comment]
So all we would need is a function that takes quantifiable values of:

Wardley
  valueChain
  evolution

Sends it to a <Map /> object, which applies a scale.

Let's change Map please to Flagstaff.

Perhaps this will be a good place for a factor function. Like make three of those components independently, and the Flagstaff factory would handle any edge case bugs regarding clipping, or UX ?

**Comment by urgent** [comment]
I guess we don't even need d3 !

**Comment by adammankowski1** [comment]
I've pushed a little commit. You can adjust props valueChain evolution width height and it should generate quite equally divided flagstaff. Will do more work on it in the next week.

**Comment by urgent** [comment]
Awesome Adam, thank you. You need money?

**Comment by urgent** [comment]
Adam:

Let's talk here please instead of email.

Can I just get an HTML page of:

1. My logo in the center
2. Ad space at the bottom?

It doesn't even have to be React. I can merge your flat file changes and get you paid please.

Thanks!

**Comment by urgent** [comment]
Never mind, I'll do it today.
